---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  vars:
    molecule_labels:
      owner: molecule
    default_namespace: "default"
    default_user_name: "molecule"
    default_vm_timeout: 60
    default_vm_memory: "2Gi"
    default_vm_machine_type: "q35"
    default_vm_disk_image: "quay.io/kubevirt/fedora-cloud-container-disk-demo"
    default_ssh_timeout: 300
    default_ssh_service_type: ClusterIP
    ssh_key_path: "{{ molecule_ephemeral_directory }}/identity_{{ item.name }}"

  tasks:
    - name: Create ssh key pair
      openssh_keypair:
        path: "{{ ssh_key_path }}"
        size: 1024
        type: rsa
      loop: "{{ molecule_yml.platforms  }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Create cloud init with ssh identity for molecule user
      vars:
        user_data: |-
          {{ item.user_data | default({}) | from_yaml | combine(default_user_data | from_yaml, recursive=True, list_merge='append') }}
        default_user_data: |-
          users:
            - name: {{ item.user_name | default(default_user_name) }}
              sudo: ALL=(ALL) NOPASSWD:ALL
              plain_text_passwd: molecule
              lock_passwd: false
              ssh_authorized_keys:
                - {{ lookup('file', ssh_key_path + '.pub' ) }}
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ item.name }}"
            namespace: "{{ item.namespace | default(default_namespace) }}"
          type: Opaque
          stringData:
            userdata: |-
              #cloud-config
              {{ user_data | to_nice_yaml }}
      loop: "{{ molecule_yml.platforms  }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Create virtual machines
      vars:
        container_disk_name: "{{ item.name }}"
        domain:
          devices:
            autoattachGraphicsDevice: "{{ item.autoattachGraphicsDevice | default(false) }}"
            disks:
              - disk:
                  bus: virtio
                name: "{{ container_disk_name }}"
              - disk:
                  bus: virtio
                name: ansiblecloudinitdisk
          machine:
            type: "{{ item.machine_type | default(default_vm_machine_type) }}"
          resources:
            requests:
              memory: "{{ item.memory_request | default(item.memoy) | default(default_vm_memory) }}"
              cpu: "{{ item.cpu_request | default(item.cpu) | default(omit) }}"
            limits:
              memory: "{{ item.memory_limit | default(item.memoy) | default(default_vm_memory) }}"
              cpu: "{{ item.cpu_limit | default(item.cpu) | default(omit) }}"
        networks: "{{ item.networks | default([]) }}"
        volumes:
          - containerDisk:
              image: "{{ item.image | default(default_vm_disk_image) }}"
              path: "{{ item.image_path | default(omit) }}"
              imagePullPolicy: "{{ item.image_pull_policy | default('IfNotPresent') }}"
            name: "{{ container_disk_name }}"
          - cloudInitNoCloud:
              secretRef:
                name: "{{ item.name }}"
            name: ansiblecloudinitdisk
      k8s:
        state: present
        definition:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: "{{ item.name }}"
            namespace: default
          spec:
            running: true
            template:
              metadata:
                annotations: "{{ item.annotations | default({}) }}"
                labels:
                  vm.cnv.io/name: "{{ item.name }}"
              spec:
                domain: "{{ item.domain | default({}) | combine(domain, recursive=True, list_merge='prepend') }}"
                networks: "{{ networks }}"
                volumes: "{{ volumes + (item.volumes | default([])) }}"
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        label: "{{ item.name }}"
      register: poll_reg

    - name: Create ssh NodePort Kubernetes Services
      when: "item.ssh_service.type | default(default_ssh_service_type) == 'NodePort'"
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ item.name }}"
            namespace: "{{ item.namespace | default(default_namespace) }}"
          spec: "{{ spec | from_yaml }}"
      register: node_port_services
      loop: "{{ molecule_yml.platforms  }}"
      loop_control:
        label: "{{ item.name }}"
      # workaround https://stackoverflow.com/questions/63961938/ansible-variable-conversion-to-int-is-ignored
      vars:
        spec: |-
          ports:
            - port: 22
              protocol: TCP
              targetPort: 22
              {%- if item.ssh_service.nodePort | default(None) +%}
              nodePort: {{ item.ssh_service.nodePort | int }}
              {%- endif +%}
          selector:
            vm.cnv.io/name: "{{ item.name }}"
          type: NodePort

    - name: Create ssh ClusterIP Kubernetes Services
      when: "item.ssh_service.type | default(default_ssh_service_type) == 'ClusterIP'"
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ item.name }}"
            namespace: "{{ item.namespace | default(default_namespace) }}"
          spec:
            clusterIP: "{{ item.ssh_service.clusterIP | default(omit) }}"
            ports:
              - port: 22
                protocol: TCP
                targetPort: 22
            selector:
              vm.cnv.io/name: "{{ item.name }}"
            type: ClusterIP
      register: cluster_ip_services
      loop: "{{ molecule_yml.platforms  }}"
      loop_control:
        label: "{{ item.name }}"

    - name: SSH check block
      block:
        - name: Get ssh services info, indexed by service name
          set_fact:
            service_instance: >-
              {{ service_instance|default({}) | combine({svc_name: svc_spec}) }}
          loop: "{{ loop_services | flatten }}"
          loop_control:
            label: "{{ {svc_name: svc_spec } }}"
          vars:
            loop_services:
              - "{{ cluster_ip_services.results | rejectattr('skipped', 'true') }}"
              - "{{ node_port_services.results| rejectattr('skipped', 'true') }}"
            svc_name: "{{ item.result.metadata.name }}"
            svc_spec: "{{ item.result.spec }}"

        - name: Populate instance config dict
          set_fact:
            instance_conf_dict:
              instance: "{{ item.name }}"
              address: "{{ ssh_service_address }}"
              user: "{{ item.user_name | default('molecule') }}"
              port: "22"
              identity_file: "{{ molecule_ephemeral_directory }}/identity_{{ item.name }}"
          vars:
            # set target ssh address regarding platforms configuration
            ssh_service_address: >-
              {%- set svc_ep = item.ssh_service.type | default('ClusterIP') -%}
              {%- if svc_ep == 'NodePort' -%}
              {{ item.ssh_service.nodePort_host | default('localhost') }}:{{ service_instance[item.name].ports[item.ssh_service.nodePort_index | default(0)].nodePort }}
              {%- elif svc_ep == 'ClusterIP' -%}
              {{ service_instance[item.name].clusterIP }}
              {%- endif -%}
          register: instance_config_dict
          loop: "{{ molecule_yml.platforms }}"
          loop_control:
            label: "{{ item.name  }}"

        - name: Convert instance config dict to a list
          set_fact:
            instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"

        - name: Async start ssh access test
          wait_for:
            timeout: "{{ item.ssh_timeout | default(default_ssh_timeout) }}"
            port: "{{ item.port | default('22') }}"
            host: "{{ item.address }}"
            delay: 1
          loop: "{{ instance_conf }}"
          loop_control:
            label: "{{ {item.instance: item.address} }}"
          async: "{{ item.ssh_timeout | default(default_ssh_timeout) }}"
          poll: 0
          register: ssh_reg

        - name: SSH test
          block:
            - name: Check ssh access test
              async_status:
                jid: "{{ async_result_item.ansible_job_id }}"
              loop: "{{ ssh_reg.results }}"
              loop_control:
                loop_var: "async_result_item"
              register: async_poll_results
              until: async_poll_results.finished
              delay: 1
              retries: "{{ item['ansible_facts']['instance_conf_dict']['ssh_timeout'] | default(default_ssh_timeout) }}"
      rescue:
        - name: Failed to get ssh
          k8s_info:
            kind: "{{ item }}"
            api_version: kubevirt.io/v1alpha3
            namespace: "{{ item.namespace | default(default_namespace) }}"
          with_items:
            - Service
            - VirtualMachine
            - VirtualMachineInstance
          register: vm_info

        - name: Failed to get running VM - Dump Service, VM and VMI
          debug:
            var: dump_var
          vars:
            dump_var: "{{ item }}"
          loop: "{{ vm_info.results }}"
          failed_when: true

    - name: Dump instance config
      copy:
        content: "{{ instance_conf | to_json | from_json | to_yaml }}"
        dest: "{{ molecule_instance_config }}"
        mode: 0600
