---
dependency:
  name: galaxy
driver:
  name: kubevirt
platforms:
  - name: instance
    cdi_source_http_url: docker://quay.io/kubevirt/fedora-cloud-container-disk-demo
    cdi_pvc_size: 10Gi

provisioner:
  name: ansible
verifier:
  name: ansible
