---
dependency:
  name: galaxy
driver:
  name: kubevirt
platforms:
  - name: instance
    cdi_source_http_url: https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2c
    cdi_pvc_size: 10Gi

provisioner:
  name: ansible
verifier:
  name: ansible
