---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: molecule-kubevirt

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: molecule-kubevirt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubevirt.io:edit
subjects:
  - kind: ServiceAccount
    name: molecule-kubevirt
    namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: molecule-cdi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cdi.kubevirt.io:edit
subjects:
  - kind: ServiceAccount
    name: molecule-kubevirt
    namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: molecule-kubevirt-sec
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - services
      - persistentvolumeclaims
      - pods
      - pods/log
      - events
      - configmaps
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: molecule-kubevirt-sec
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: molecule-kubevirt-sec
subjects:
  - kind: ServiceAccount
    name: molecule-kubevirt
    namespace: default
